version: "3.7"

services:
  web:
    image: ghcr.io/bravohotel91/ipfspodcastnode:latest
    init: true
    restart: on-failure
    stop_grace_period: 1m
    user: "1000:1000"
    ports:
      - 4001:4001  # IPFS
      - 8675:8675  # Web UI
    volumes:
      - ${APP_DATA_DIR}/ipfs:/ipfs-podcasting/ipfs
      - ${APP_DATA_DIR}/cfg:/ipfs-podcasting/cfg
