name: Deploy Container

# Run workflow on main branch
on:
  push:
    branches:
      - "main"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5.1.0
        with:
          push: true # Will only build if this is not here
          tags: | 
            ghcr.io/${{ github.repository }}:latest
